# Students : Hazim Benslimane, Christopher Jabea, Dylan Rachwal, Alexandre Thouvenot 

## Project of Machine learning for classification on the 2 datasets Banknote Authentication and Chronic Kidney Disease

In [10]:
%matplotlib inline
%pylab inline
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd
from sklearn import svm
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, ShuffleSplit
from sklearn.tree import export_graphviz
from graphviz import Source
from functions import *


mpl.style.use("ggplot")

Populating the interactive namespace from numpy and matplotlib


In [11]:
X,Y,class_labels = load_data("data_banknote_authentication")
print(X)
print(Y)

[[  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 [  3.4566    9.5228   -4.0112   -3.5944 ]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]
[0 0 0 ... 1 1 1]


In [12]:
X_train, X_test, Y_train, Y_test = split_data(X, Y, 900)

In [13]:
Y_pred = predict_SVC(X_train, X_test, Y_train)

In [14]:
precisions, recalls = precision_recall_multilabels(Y_test,Y_pred,class_labels)
print(precisions)
print(recalls)

[[0.99610895 1.        ]]
[[1.         0.99534884]]
